// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1xykE2tanuO-E1KYRBHxgbQ5cOFLxtvg',
    appId: '1:623254871252:web:bba4448cc985b4a1882f41',
    messagingSenderId: '623254871252',
    projectId: 'eth-ride-f0c3e',
    authDomain: 'eth-ride-f0c3e.firebaseapp.com',
    storageBucket: 'eth-ride-f0c3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEctTUfraPsQ3jETULgTFBEH-ZNxwSbnQ',
    appId: '1:623254871252:android:453a79aca45c8eee882f41',
    messagingSenderId: '623254871252',
    projectId: 'eth-ride-f0c3e',
    storageBucket: 'eth-ride-f0c3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw7TGENJakdrxBDsO5Hcf1ZobB9wKuob0',
    appId: '1:623254871252:ios:2db77585fa482bc9882f41',
    messagingSenderId: '623254871252',
    projectId: 'eth-ride-f0c3e',
    storageBucket: 'eth-ride-f0c3e.appspot.com',
    iosBundleId: 'com.example.ethRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw7TGENJakdrxBDsO5Hcf1ZobB9wKuob0',
    appId: '1:623254871252:ios:820946cf8f3ab325882f41',
    messagingSenderId: '623254871252',
    projectId: 'eth-ride-f0c3e',
    storageBucket: 'eth-ride-f0c3e.appspot.com',
    iosBundleId: 'com.example.ethRide.RunnerTests',
  );
}
